sudo: required
services:
  - docker
addons:
  firefox: latest
env:
  - MOZ_HEADLESS=1
notifications:
  email:
    recipients:
      - leidy.carvajal.o@correounivalle.edu.co
      - julian.silva@correounivalle.edu.co
      - alexander.redondo@correounivalle.edu.co
      - fredy.ballesteros@correounivalle.edu.co
    on_success: always # default: change
    on_failure: always # default: always
before_install:
  - docker pull selenium/node-firefox:3.8.1-francium
  - docker pull selenium/hub:3.8.1-francium
  - docker run -d -p 4444:4444 --name selenium-hub selenium/hub:3.8.1-francium
  - docker run -d --link selenium-hub:hub --name selenium-node-firefox -v /dev/shm:/dev/shm selenium/node-firefox:3.8.1-francium
  - docker build -t fredyball/django-client ./prodjango

script:
  - docker run fredyball/django-client python manage.py test

after_success:
  - echo "LISTO EL POLLO ASADO"